#
# Azure pipeline template for build.
#
# Copyright (c) Microsoft Corporation. All rights reserved.
##

jobs:
  - job: build_and_test
    displayName: Build and Test the QEMU Rust DXE Core

    timeoutInMinutes: 30

    workspace:
      clean: all

    pool:
      vmImage: 'windows-latest'

    variables:
      - group: "UEFI Rust Tokens"

    steps:
    - checkout: self
      fetchDepth: 1
      clean: true

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.12'
      inputs:
        versionSpec: '3.12.x'
        architecture: 'x64'

    - template: Steps/InstallMarkdownLint.yml@mu_devops
    - template: Steps/RunMarkdownLint.yml@mu_devops
    - template: Steps/InstallSpellCheck.yml@mu_devops
    - template: Steps/RunSpellCheck.yml@mu_devops
      parameters:
        spell_check_parameters: "-c cspell.yml **/*.md **/*.py **/*.rs"

    - template: Steps/RustSetupSteps.yml@mu_devops

    - task: PowerShell@2
      displayName: Setup Cred Provider
      inputs:
        targetType: 'inline'
        script: |
          $cargoPath = Join-Path -Path $env:USERPROFILE -ChildPath ".cargo"
          $configPath = "$cargoPath\config.toml"
          New-Item -ItemType Directory -Force -Path "$cargoPath\.cargo" | Out-Null
          "[registry]" | Out-File -Encoding "UTF8" -Append -FilePath $configPath
          'global-credential-providers = ["cargo:token"]' | Out-File -Encoding "UTF8" -Append -FilePath $configPath
          "" | Out-File -Encoding "UTF8" -Append -FilePath $configPath

    # Run a powershell script to conver the job access token using ""Basic " + [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("PAT:" + "123abc"))" to an output variable
    - task: PowerShell@2
      displayName: Convert Registry Token
      name: ConvertRegistryToken
      inputs:
        targetType: 'inline'
        script: |
          $pat = "$(msuefi-authpat)"
          $base64 = "Basic " + [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("PAT:" + $pat))
          Write-Host "##vso[task.setvariable variable=base64Pat;isOutput=true;]$base64"

    - script: cargo login "$(ConvertRegistryToken.base64Pat)" --registry UefiRust
      displayName: Login to Registry

    - template: Steps/RustCargoSteps.yml@mu_devops
      parameters:
        build_command: >-
          cmd /V /C "set RUSTC_BOOTSTRAP=1&&cargo build_q35&&cargo build_q35 --profile=release && cargo build_sbsa && cargo build_sbsa --profile=release"
        format_command: >-
          cmd /V /C "set RUSTC_BOOTSTRAP=1&&cargo fmt --all --check"
        test_command: >-
          cmd /V /C "set RUSTC_BOOTSTRAP=1&&cargo test"

    - task: CopyFiles@2
      displayName: "Stage Debug Binaries"
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)/Bin/debug'
        SourceFolder: 'target'
        contents: |
            **/debug/qemu_q35_dxe_core.efi
            **/debug/qemu_q35_dxe_core.pdb
            **/debug/qemu_sbsa_dxe_core.efi
            **/debug/qemu_sbsa_dxe_core.pdb
        flattenFolders: true
      condition: Succeeded()

    - task: CopyFiles@2
      displayName: "Stage Release Binaries"
      inputs:
        targetFolder: '$(Build.ArtifactStagingDirectory)/Bin/release'
        SourceFolder: 'target'
        contents: |
            **/release/qemu_q35_dxe_core.efi
            **/release/qemu_q35_dxe_core.pdb
            **/release/qemu_sbsa_dxe_core.efi
            **/release/qemu_sbsa_dxe_core.pdb
        flattenFolders: true
      condition: Succeeded()

    - task: PublishBuildArtifacts@1
      continueOnError: true
      displayName: Publish Binaries
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/Bin'
        artifactName: 'Bin'
      condition: Succeeded()
