[package]
name = "qemu_dxe_core"
version = "0.0.2"
edition = "2021"

[[bin]]
name = "qemu_q35_dxe_core"
path = "bin/q35_dxe_core.rs"
required-features = ["x64"]

[[bin]]
name = "qemu_sbsa_dxe_core"
path = "bin/sbsa_dxe_core.rs"
required-features = ["aarch64"]

[dependencies]
section_extractor = { git = "https://github.com/pop-project/uefi-core.git", rev = "v6.0.1" }
uefi_cpu = { git = "https://github.com/pop-project/uefi-core.git", rev = "v6.0.1" }
uefi_debugger = { git = "https://github.com/pop-project/uefi-core.git", rev = "v6.0.1" }

adv_logger = { git = "https://github.com/pop-project/uefi-dxe-core.git", rev = "v6.0.0" }
dxe_core = { git = "https://github.com/pop-project/uefi-dxe-core.git", rev = "v6.0.0" }
sample_components = { git = "https://github.com/pop-project/uefi-dxe-core.git", rev = "v6.0.0" }

uefi_sdk = { git = "https://github.com/pop-project/uefi-sdk.git", rev = "v0.1.2" }


log = { version = "^0.4", default-features = false, features = [
    "release_max_level_warn",
] }

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0

[features]
default = []
x64 = []
aarch64 = []
