[package]
name = "qemu_dxe_core"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "qemu_q35_dxe_core"
path = "bin/q35_dxe_core.rs"
required-features = ["x64"]

[[bin]]
name = "qemu_sbsa_dxe_core"
path = "bin/sbsa_dxe_core.rs"
required-features = ["aarch64"]

[dependencies]
section_extractor = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}
serial_writer = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}
uefi_cpu_init = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}
uefi_interrupt = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}
uefi_logger = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}

adv_logger = {git = "https://github.com/pop-project/uefi-dxe-core.git", rev = "2853304e90c816a0404e680a687ccabfbb6ef6aa"}
dxe_core = {git = "https://github.com/pop-project/uefi-dxe-core.git", rev = "2853304e90c816a0404e680a687ccabfbb6ef6aa"}
sample_components = {git = "https://github.com/pop-project/uefi-dxe-core.git", rev = "2853304e90c816a0404e680a687ccabfbb6ef6aa"}

log = { version = "^0.4", default-features = false, features = ["release_max_level_warn"]}

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0

[features]
default = []
x64 = []
aarch64 = []
