[package]
name = "qemu_dxe_core"
version = "0.4.0"
edition = "2024"
license = "BSD-2-Clause-Patent"

[[bin]]
name = "qemu_q35_dxe_core"
path = "bin/q35_dxe_core.rs"
required-features = ["x64"]

[[bin]]
name = "qemu_sbsa_dxe_core"
path = "bin/sbsa_dxe_core.rs"
required-features = ["aarch64"]

[lib]
name = "qemu_resources"
path = "src/lib.rs"

[dependencies]
log = { version = "^0.4", default-features = false, features = [
    "release_max_level_warn",
] }
patina_adv_logger = { version = "5", registry = "patina-fw" }
patina_debugger = { version = "5", registry = "patina-fw" }
patina_dxe_core = { version = "5", registry = "patina-fw" }
patina_mm = { version = "5", registry = "patina-fw" }
patina_samples = { version = "5", registry = "patina-fw" }
patina_sdk = { version = "5", registry = "patina-fw", features = ["enable_patina_tests"] }
patina_section_extractor = { version = "5", registry = "patina-fw" }
patina_stacktrace = { version = "5", registry = "patina-fw" }
r-efi = { version = "^5", default-features = false }
x86_64 = { version = "=0.15.2", default-features = false, features = [
  "instructions"
], optional = true }

# These release settings reduce the qemu binary size significantly(~35%).
[profile.release]
codegen-units = 1
debug = "full"
lto = true
opt-level = "s"
split-debuginfo = "packed"
strip = "symbols"
incremental = true

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0

[features]
default = ["compatibility_mode_allowed"]
compatibility_mode_allowed = ["patina_dxe_core/compatibility_mode_allowed"]
x64 = ["x86_64"]
aarch64 = []
doc = []
std = []
