# GitHub Issue Configuration File
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
blank_issues_enabled: false
contact_links:
  - name: 📃 Documentation
    url: https://OpenDevicePartnership.github.io/patina-dxe-core-qemu/
    about: Goals, principles, repo layout, build instructions, and more.
