[alias]
build_q35 = "build --bin qemu_q35_dxe_core --target x86_64-unknown-uefi --features=x64 -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -Zunstable-options --timings=html"
build_sbsa = "build --bin qemu_sbsa_dxe_core --target aarch64-unknown-uefi --features=aarch64 -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -Zunstable-options --timings=html"
