author_string: Microsoft Corporation
copyright_string: Copyright (c) Microsoft Corporation
description_string: QEMU DXE Core
license_url: http://www.microsoft.com/
name: DXECORE.QEMU
project_url: https://microsoft.github.com/mu
server_url: https://pkgs.dev.azure.com/patina-fw/artifacts/_packaging/qemu-dxe-core/nuget/v3/index.json
tags_string: ''
