## @file
# Azure Pipeline build file for the repository
#
# Copyright (c) Microsoft Corporation. All rights reserved.
##

trigger: none
pr: none

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

jobs:
- template: templates/Build.yml

