## @file
# Azure Pipeline build file to make an QEMU Rust DXE Core binary release.
#
# Copyright (c) Microsoft Corporation. All rights reserved.
##

trigger: none
pr: none

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

parameters:
# The package version should always be specified and accurate.
- name: nuget_package_version
  displayName: Nuget Package Version
  type: string
  default: ''

jobs:
- template: templates/Build.yml
- template: templates/Nuget.yml
  parameters:
    nuget_package_version: ${{ parameters.nuget_package_version }}
