# @file publish-binaries.yml
#
# A workflow for publishing QEMU DXE Core binaries.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Publish Binaries

    runs-on: windows-latest

    permissions:
      contents: write
      actions: read

    steps:
      - name: ✅ Checkout Repository ✅
        uses: actions/checkout@v4

      - name: 🛠️ Download Rust Tools 🛠️
        uses: OpenDevicePartnership/patina/.github/actions/rust-tool-cache@main

      - name: Build Q35 Debug
        run: cargo make q35

      - name: Build SBSA Debug
        run: cargo make sbsa

      - name: Build Q35 Release
        run: cargo make q35-release

      - name: Build SBSA Release
        run: cargo make sbsa-release

      - name: Collect Binaries
        run: |
          # Create a directory for the release artifacts
          mkdir -p "artifacts/debug"
          mkdir -p "artifacts/release"

          # Copy the binaries to the artifacts directory
          cp target/x86_64-unknown-uefi/debug/qemu_q35_dxe_core.efi artifacts/debug/qemu_q35_dxe_core.efi
          cp target/x86_64-unknown-uefi/debug/qemu_q35_dxe_core.pdb artifacts/debug/qemu_q35_dxe_core.pdb
          cp target/x86_64-unknown-uefi/release/qemu_q35_dxe_core.efi artifacts/release/qemu_q35_dxe_core.efi
          cp target/x86_64-unknown-uefi/release/qemu_q35_dxe_core.pdb artifacts/release/qemu_q35_dxe_core.pdb
          cp target/aarch64-unknown-uefi/debug/qemu_sbsa_dxe_core.efi artifacts/debug/qemu_sbsa_dxe_core.efi
          cp target/aarch64-unknown-uefi/debug/qemu_sbsa_dxe_core.pdb artifacts/debug/qemu_sbsa_dxe_core.pdb
          cp target/aarch64-unknown-uefi/release/qemu_sbsa_dxe_core.efi artifacts/release/qemu_sbsa_dxe_core.efi
          cp target/aarch64-unknown-uefi/release/qemu_sbsa_dxe_core.pdb artifacts/release/qemu_sbsa_dxe_core.pdb

      - name: Upload Binaries
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: qemu-dxe-core
          path: artifacts/

      - name: Publish Release Asset
        if: ${{ github.event_name == 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Compress-Archive -Path artifacts/* -DestinationPath patina_dxe_core_qemu.zip
          gh release upload ${{ github.event.release.tag_name }} patina_dxe_core_qemu.zip

      # The following steps may be removed when the releases are publically available.

      - name: Get Release Tag
        if: ${{ github.event_name == 'release' }}
        id: release_tag
        run: |
          tag_name="${{ github.event.release.tag_name }}"

          # remove the leading 'v' if it exists
          release_tag="${tag_name#v}"

          echo "Release Tag: $release_tag"
          echo "TAG=$release_tag" >> $GITHUB_ENV
        shell: bash

      - name: Set up Python
        if: ${{ github.event_name == 'release' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Publish Nuget
        if: ${{ github.event_name == 'release' }}
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
          LICENSE_FILE_PATH: .nuget/license.txt
          NUGET_PACKAGE_CONFIG_FILE_PATH: .nuget/dxe_core_config.yaml
          CONTENTS_PATH: artifacts/
        run: |
          apiKey=$NUGET_KEY
          configFilePath=$NUGET_PACKAGE_CONFIG_FILE_PATH
          customLicensePath=$GITHUB_WORKSPACE/$LICENSE_FILE_PATH
          inputFolderPath=$CONTENTS_PATH
          packageVersion=$TAG
          pip install edk2-pytool-extensions
          nuget-publish --Operation PackAndPush --ConfigFilePath "$configFilePath" --InputFolderPath "$inputFolderPath" --Version "$packageVersion" --ApiKey "$apiKey" --CustomLicensePath "$customLicensePath"
        shell: bash
