# Specifies labels to apply to issues and pull requests based on file path patterns in Patina repositories.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
# For more information, see:
# https://github.com/actions/labeler

# Maintenance: Keep labels organized in ascending alphabetical order - easier to scan, identify duplicates, etc.

language:python:
    - '**/*.py'
